/*
=======================================================================================================================================================================================================
SUBJECT		 : Reference table housing category listings found on various job search sites
OBJECT TYPE	 : TABLE
OBJECT NAME	 : ltn.dbo.ref_jobsearch_cat_list
CREATED BY	 : Harold Delaney
CREATED ON	 : 20161014
SOURCE		 : 
PREPERATION	 : CREATE TABLE
			   INSERT VALUES REQUIRED FOR IDENTIFICATION OF STAGING RESULTS
REMARKS		 : 1) 
			   2)
			   3)
 
=======================================================================================================================================================================================================

TABLE CREATION
-----------------------------

drop table ltn.dbo.ref_jobsearch_cat_list;

CREATE TABLE ltn.dbo.ref_jobsearch_cat_list
             (
             start_dte_id       int NOT NULL
           , end_dte_id         int NOT NULL
           , js_site_desc_short varchar(25) NOT NULL
           , js_job_cat         varchar(50) NOT NULL
           , incl_flag          varchar(3) NOT NULL
             );

CREATE NONCLUSTERED INDEX ix_ref_jobsearch_cat_list ON ltn.dbo.ref_jobsearch_cat_list(end_dte_id,js_site_desc_short);

ALTER TABLE ltn.dbo.ref_jobsearch_cat_list REBUILD
WITH(DATA_COMPRESSION = ROW);
=======================================================================================================================================================================================================
*/
truncate table LTN.DBO.REF_JOBSEARCH_CAT_LIST;

/*
=======================================================================================================================================================================================================
CATEGORY LIST FOR ADZUNA
=======================================================================================================================================================================================================
*/
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','ACCOUNTING & FINANCE','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','ADMIN','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','CHARITY & VOLUNTARY','NO');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','CONSULTANCY','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','CREATIVE & DESIGN','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','CUSTOMER SERVICES','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','DOMESTIC HELP & CLEANING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','ENERGY, OIL & GAS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','ENGINEERING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','GRADUATE','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','HR & RECRUITMENT','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','HEALTHCARE & NURSING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','HOSPITALITY & CATERING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','IT','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','LEGAL','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','LOGISTICS & WAREHOUSE','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','MAINTENANCE','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','MANUFACTURING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','OTHER/GENERAL','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','PR, ADVERTISING & MARKETING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','PART TIME','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','PROPERTY','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','RETAIL','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','SALES','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','SCIENTIFIC & QA','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','SOCIAL WORK','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','TEACHING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','TRADE & CONSTRUCTION','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'ADZUNA','TRAVEL','YES');

/*
=======================================================================================================================================================================================================
CATEGORY LIST FOR JOBSERVE
=======================================================================================================================================================================================================
*/
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','ADVERTISING, MEDIA & ENTERTAINMENT','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','CALL CENTRE & CUSTOMER SERVICES','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','CONSTRUCTION & CIVIL ENGINEERING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','MILITARY & ARMED FORCES','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','EDUCATION','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','ENGINEERING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','FINANCE, ACCOUNTING & BANKING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','FOOD & HOSPITALITY','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','HEALTHCARE & MEDICAL','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','HR & RECRUITMENT','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','IT & TELECOMMUNICATIONS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','LEGAL','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','MANUFACTURING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','MINING, ENERGY, OIL & GAS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','OFFICE & ADMINISTRATION','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','RETAIL & CONSUMER PRODUCTS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','SALES & MARKETING','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','SCIENCE, BIOTECH & PHARMACEUTICALS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','TRADES & SERVICES','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','TRANSPORT & LOGISTICS','YES');
INSERT INTO LTN.DBO.REF_JOBSEARCH_CAT_LIST VALUES (20161014, 29991231, 'JOBSERVE','TRAVEL & TOURISM','YES');

/*
=======================================================================================================================================================================================================
CATEGORY LIST FOR 
=======================================================================================================================================================================================================
*/


select * from ltn.dbo.ref_jobsearch_cat_list