/*
=======================================================================================================================================================================================================
SUBJECT		 : Control table housing variables required for automating/running python packages
OBJECT TYPE	 : TABLE
OBJECT NAME	 : PY_VARS_TWEEP_CTL
CREATED BY	 : Harold Delaney
CREATED ON	 : 20170627
SOURCE	 : 
PREPERATION	 : CREATE TABLE INSERT VALUES REQUIRED FOR SSIS RUNNING
REMARKS	 : 1) 
           2)
           3)
 
=======================================================================================================================================================================================================
TABLE CREATION
-----------------------------

DROP TABLE PY_VARS_TWEEP_CTL;

CREATE TABLE PY_VARS_TWEEP_CTL (
    id        INTEGER        PRIMARY KEY AUTOINCREMENT,
    ENV       VARCHAR (6)    NOT NULL,
    PKG_NME   VARCHAR (150),
    VAR_TYPE  VARCHAR (6)    NOT NULL,
    VAR_NME   VARCHAR (150)  NOT NULL,
    VAR_VAL   VARCHAR (2000) NOT NULL,
    VAR_CMNTS VARCHAR (2000) NOT NULL
);
=======================================================================================================================================================================================================

select * from PY_VARS_TWEEP_CTL

*/

delete from PY_VARS_TWEEP_CTL;

-- ENVIRONMENT PARAMETERS 
-- PROD
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','EMAIL_SNDR_USRNME','lanoitan17@gmail.com','email sender username/address for email notifications');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','EMAIL_SNDR_PWORD','500BourkeStreet','email sender password');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','EMAIL_DSTRBTN_LST','toshach@gmail.com','email distribution list for email notifications');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','DATA_RETENTION_DAYS','10','number of days to keep data within sqlite tables.  is overridden if a pkg variable is present');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','EMAIL_MSG','','generic email message. is overridden if pkg variable is present');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_CNSMR_KEY','EO3DcdljWwxN4TKrUUB27Nn96','api key');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_CNSMR_SECRET','H9XFfndnoGXrepH5RQA9N2hCaSWJHNV66t9DXXz5DDF1CPXJWp','api secret');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_ACCESS_TOKEN','12577272-frRvqnqx1IfaKuwy5aOe172ppKeBL2ta6AAUtsQns','access token');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_ACCESS_SECRET','qfneff6FA12lz3otz4jdXFEQZqyplrrAJuqlZUAe7hEpI','access token secret');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_MAX_TWEETS','10000000','arbitrary large number to use for the REST api of tweepy to maximise output');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','','ENV','TWIT_TWEETS_PER_QRY','100','1009 is the maximum the tweepy api permits');
-- DEV
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','EMAIL_SNDR_USRNME','lanoitan17@gmail.com','email sender username/address for email notifications');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','EMAIL_SNDR_PWORD','500BourkeStreet','email sender password');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','EMAIL_DSTRBTN_LST','toshach@gmail.com','email distribution list for email notifications');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','DATA_RETENTION_DAYS','10','number of days to keep data within sqlite tables.  is overridden if a pkg variable is present');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','EMAIL_MSG','','generic email message. is overridden if pkg variable is present');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_CNSMR_KEY','EO3DcdljWwxN4TKrUUB27Nn96','api key');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_CNSMR_SECRET','H9XFfndnoGXrepH5RQA9N2hCaSWJHNV66t9DXXz5DDF1CPXJWp','api secret');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_ACCESS_TOKEN','12577272-frRvqnqx1IfaKuwy5aOe172ppKeBL2ta6AAUtsQns','access token');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_ACCESS_SECRET','qfneff6FA12lz3otz4jdXFEQZqyplrrAJuqlZUAe7hEpI','access token secret');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_MAX_TWEETS','10000000','arbitrary large number to use for the REST api of tweepy to maximise output');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','','ENV','TWIT_TWEETS_PER_QRY','100','1009 is the maximum the tweepy api permits');


/* 
==============================================================================================================================
TWITTER 
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS_AU','PKG','KEY_PHRASES_NEG_ALL','"am dismissed","am redundant","axed","be fired","been dismissed","been fired","been sacked","being fired","canned","down sized","downsized","fired from","get fired","got fired","got sacked","just fired","laid off","laidoff","lay off","layed off","layoff","made redundant","outsourced","pink slip","pinkslip","unemploy","unemployed","unemployment","was dismissed","was fired","lost job","lost my job","lost the job","fired from job","fired from my job","fired from the job","fired from work","fired from my work","fired from the work","got sack","got the sack"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS_AU','PKG','KEY_PHRASES_POS_ALL','"job opportunities","job opportunity","work opportunities","work opportunity","jobs near","job near","work near","find a job","find new job","find a new job","find myself a job","find myself a new job","find work","find some work","find some new work","find new work","find myself work","find some work","find some new work","look for job","look for a job","look for new job","look for a new job","looking for job","looking for a job","looking for new job","looking for a new job","looking for any job","look for work","look for new work","look for some work","look for some new work","looking for work","looking for new work","looking for some work","looking for some new work","looking for any work","need new job","need a new job","need a job","need work","need some work","need some new work","search for job","search for a job","search for a new job","looking for job","looking for new job","looking for some new job","looking for any job","search for work","search for work","search for new work","searching for work","searching for new work","searching for some work","searching for some new work","searching for any work","seek job","seek a job","seek new job","seek a new job","seeking job","seeking a job","seeking a new job","seeking for job","seeking any job","seek position","seek a position","seek new position","seek a new position","seeking position","seeking new position","seeking some position","seeking some new position","seeking any position","seek work","seek new work","seek some work","seek some new work","seeking work","seeking new work","seeking some work","seeking some new work","seeking any work","hiring for","hiring at","hiring in","jobs near"','key terms and phrases to capture through twitter - specific to job losses and application');
============================================================================================================================== 
*/
-- PY_BATCH_TWEEPS (CONTROLS WHAT SCRIPTS IN THE "COMPETITOR" FOLDER ARE RUN)
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_BATCH_TWITTER','PKG','ACTIVE_IND','Y','used to bypass from a variables perspective (rather than turning off in BATCH script)');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_BATCH_TWITTER','PKG','PKGS_TO_RUN','PY_TWITTER_REST_JOBS','list of packages to be run within the current folder (comma(,) delimeted)');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_BATCH_TWITTER','PKG','SMRY_DESC','(NA)','batch controller - this package is used to fire packages located in same folder and listed in the PKG_TO_RUN variable');
-- PY_TWITTER_STREAM
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','ACTIVE_IND','Y','used to bypass from a variables perspective (rather than turning off in BATCH script)');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','SMRY_DESC','(NA)','using tweepy, scan tweets from twitter for key terms and phrases.  multiple subject areas may be present and seperating these programatically may be necessary');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','TBL_NME','PY_TWEEP_DATA','table name for the scrape results to be posted to');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','COUNTRY_RESTRICTIONS','AU,CA,NZ,GB,US','');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','KEY_PHRASES_JLU','am dismissed,am redundant,axed,be fired,been dismissed,been fired,been sacked,being fired,canned,down sized,downsized,fired from,get fired,got fired,got sacked,just fired,laid off,laidoff,lay off,layed off,layoff,made redundant,outsourced,pink slip,pinkslip,unemploy,unemployed,unemployment,was dismissed,was fired,lost job,lost my job,lost the job,fired from job,fired from my job,fired from the job,fired from work,fired from my work,fired from the work,got sack,got the sack','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','KEY_PHRASES_JSJP','job opportunities,job opportunity,work opportunities,work opportunity,jobs near,job near,work near,find a job,find new job,find a new job,find myself a job,find myself a new job,find work,find some work,find some new work,find new work,find myself work,find some work,find some new work,look for job,look for a job,look for new job,look for a new job,looking for job,looking for a job,looking for new job,looking for a new job,looking for any job,look for work,look for new work,look for some work,look for some new work,looking for work,looking for new work,looking for some work,looking for some new work,looking for any work,need new job,need a new job,need a job,need work,need some work,need some new work,search for job,search for a job,search for a new job,looking for job,looking for new job,looking for some new job,looking for any job,search for work,search for work,search for new work,searching for work,searching for new work,searching for some work,searching for some new work,searching for any work,seek job,seek a job,seek new job,seek a new job,seeking job,seeking a job,seeking a new job,seeking for job,seeking any job,seek position,seek a position,seek new position,seek a new position,seeking position,seeking new position,seeking some position,seeking some new position,seeking any position,seek work,seek new work,seek some work,seek some new work,seeking work,seeking new work,seeking some work,seeking some new work,seeking any work,hiring for,hiring at,hiring in,jobs near','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','KEY_PHRASES_JLU_ORIG','am dismissed,am redundant,axed,be fired,been dismissed,been fired,been sacked,being fired,canned,down sized,downsized,fired from,get fired,got fired,got sacked,just fired,laid off,laidoff,lay off,layed off,layoff,made redundant,outsourced,pink slip,pinkslip,unemploy,unemployed,unemployment,was dismissed,was fired,lost job,lost my job,lost the job,fired from job,fired from my job,fired from the job,fired from work,fired from my work,fired from the work,got sack,got the sack','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','KEY_PHRASES_JSJP_ORIG','job opportunities,job opportunity,work opportunities,work opportunity,jobs near,job near,work near,find a job,find new job,find a new job,find myself a job,find myself a new job,find work,find some work,find some new work,find new work,find myself work,find some work,find some new work,look for job,look for a job,look for new job,look for a new job,looking for job,looking for a job,looking for new job,looking for a new job,looking for any job,look for work,look for new work,look for some work,look for some new work,looking for work,looking for new work,looking for some work,looking for some new work,looking for any work,need new job,need a new job,need a job,need work,need some work,need some new work,search for job,search for a job,search for a new job,looking for job,looking for new job,looking for some new job,looking for any job,search for work,search for work,search for new work,searching for work,searching for new work,searching for some work,searching for some new work,searching for any work,seek job,seek a job,seek new job,seek a new job,seeking job,seeking a job,seeking a new job,seeking for job,seeking any job,seek position,seek a position,seek new position,seek a new position,seeking position,seeking new position,seeking some position,seeking some new position,seeking any position,seek work,seek new work,seek some work,seek some new work,seeking work,seeking new work,seeking some work,seeking some new work,seeking any work,hiring for,hiring at,hiring in,jobs near','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_STREAMING','PKG','KEY_PHRASES_CRYPTOCCY','','key terms and phrases to capture through twitter - specific to crypto currency sentiment');
-- PY_TWITTER_REST_JOBS
-- PROD
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','ACTIVE_IND','Y','used to bypass from a variables perspective (rather than turning off in BATCH script)');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','SMRY_DESC','(NA)','using tweepy, scan tweets from twitter for key terms and phrases.  multiple subject areas may be present and seperating these programatically may be necessary');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','TBL_NME','PY_TWEEP_DATA','table name for the scrape results to be posted to');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','CNTRY_CDE','AU,CA,NZ,UK,US','regions to pull tweets from');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_TEST','"donald trump","australian survivor"','test');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_1','"am dismissed","am redundant","axed","be fired","been dismissed","been fired","been sacked","being fired","canned","down sized","downsized","fired from","get fired","got fired","got sacked","just fired","laid off","laidoff"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_2','"lay off","layed off","layoff","made redundant","outsourced","pink slip","pinkslip","unemploy","unemployed","unemployment","was dismissed","was fired","lost job","lost my job","lost the job","fired from job","fired from my job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_3','"fired from the job","fired from work","fired from my work","fired from the work","got sack","got the sack"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_1','"job opportunities","job opportunity","work opportunities","work opportunity","jobs near","job near","work near","find a job","find new job","find a new job","find myself a job","find myself a new job","find work","find some work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_2','"find some new work","find new work","find myself work","find some work","find some new work","look for job","look for a job","look for new job","look for a new job","looking for job","looking for a job","looking for new job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_3','"looking for a new job","looking for any job","look for work","look for new work","look for some work","look for some new work","looking for work","looking for new work","looking for some work","looking for some new work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_4','"looking for any work","need new job","need a new job","need a job","need work","need some work","need some new work","search for job","search for a job","search for a new job","looking for job","looking for new job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_5','"looking for some new job","looking for any job","search for work","search for work","search for new work","searching for work","searching for new work","searching for some work","searching for some new work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_6','"searching for any work","seek job","seek a job","seek new job","seek a new job","seeking job","seeking a job","seeking a new job","seeking for job","seeking any job","seek position","seek a position","seek new position"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_7','"seek a new position","seeking position","seeking new position","seeking some position","seeking some new position","seeking any position","seek work","seek new work","seek some work","seek some new work","seeking work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('PROD','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_8','"seeking new work","seeking some work","seeking some new work","seeking any work","hiring for","hiring at","hiring in","jobs near"','key terms and phrases to capture through twitter - specific to job losses and application');
-- DEV
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','ACTIVE_IND','Y','used to bypass from a variables perspective (rather than turning off in BATCH script)');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','SMRY_DESC','(NA)','using tweepy, scan tweets from twitter for key terms and phrases.  multiple subject areas may be present and seperating these programatically may be necessary');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','TBL_NME','PY_TWEEP_DATA','table name for the scrape results to be posted to');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','CNTRY_CDE','AU,CA,NZ,UK,US','regions to pull tweets from');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_TEST','"donald trump","australian survivor"','test');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_1','"am dismissed","am redundant","axed","be fired","been dismissed","been fired","been sacked","being fired","canned","down sized","downsized","fired from","get fired","got fired","got sacked","just fired","laid off","laidoff"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_2','"lay off","layed off","layoff","made redundant","outsourced","pink slip","pinkslip","unemploy","unemployed","unemployment","was dismissed","was fired","lost job","lost my job","lost the job","fired from job","fired from my job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_NEG_3','"fired from the job","fired from work","fired from my work","fired from the work","got sack","got the sack"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_1','"job opportunities","job opportunity","work opportunities","work opportunity","jobs near","job near","work near","find a job","find new job","find a new job","find myself a job","find myself a new job","find work","find some work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_2','"find some new work","find new work","find myself work","find some work","find some new work","look for job","look for a job","look for new job","look for a new job","looking for job","looking for a job","looking for new job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_3','"looking for a new job","looking for any job","look for work","look for new work","look for some work","look for some new work","looking for work","looking for new work","looking for some work","looking for some new work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_4','"looking for any work","need new job","need a new job","need a job","need work","need some work","need some new work","search for job","search for a job","search for a new job","looking for job","looking for new job"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_5','"looking for some new job","looking for any job","search for work","search for work","search for new work","searching for work","searching for new work","searching for some work","searching for some new work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_6','"searching for any work","seek job","seek a job","seek new job","seek a new job","seeking job","seeking a job","seeking a new job","seeking for job","seeking any job","seek position","seek a position","seek new position"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_7','"seek a new position","seeking position","seeking new position","seeking some position","seeking some new position","seeking any position","seek work","seek new work","seek some work","seek some new work","seeking work"','key terms and phrases to capture through twitter - specific to job losses and application');
insert into PY_VARS_TWEEP_CTL (ENV, PKG_NME, VAR_TYPE, VAR_NME, VAR_VAL, VAR_CMNTS) values ('DEV','PY_TWITTER_REST_JOBS','PKG','KEY_PHRASES_POS_8','"seeking new work","seeking some work","seeking some new work","seeking any work","hiring for","hiring at","hiring in","jobs near"','key terms and phrases to capture through twitter - specific to job losses and application');





