/*
=====================================================================================================================================================
SUBJECT		 : Table 19. Monthly hours worked in all jobs by Employed full-time, part-time and Sex and by State and Territory - Trend and Seasonally adjusted 
TABLE NAME	 : ltn.dbo.f_dtl_labour_force_status_m
CREATED BY	 : Harold Delaney
CREATED ON	 : 20160812
SOURCE		 : ABS [ http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/6202.0Jun%202016?OpenDocument ]
			   ID - 6202019
PREPERATION	 : COPY	   - "Data1" (just the data - no headings) to new workbook
			   TRANSFORM - format date so that is yyyy-mm-dd
			   TRANSFORM - set ALL columns to 7 point data precision (7 decimal places for value and percentages)
			   SAVE	   - as .csv as same name to F:\__lanoitan\__data

REMARKS		 : 1) 
			   2)
			   3)
 
=====================================================================================================================================================

TABLE CREATION
-----------------------------

DROP TABLE ltn.dbo.f_dtl_labour_force_hrs_wrkd_m;

CREATE TABLE LTN.DBO.F_DTL_LABOUR_FORCE_HRS_WRKD_M
( MSMT_DTE_ID                                                                      integer NOT NULL
, CAPTURE_PERIOD_ID                                                                integer NOT NULL
, CAPTURE_PERIOD                                                                   date NOT NULL
, CNTRY_CDE                                                                        varchar(2) NOT NULL
, SITE_CDE                                                                         varchar(20) NOT NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND                                  decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED                    decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND                                    decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED                      decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND                                  decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED                    decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND               decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND                 decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED   decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND               decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND               decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND                  decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED    decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND               decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND                          decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED            decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND                                 decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED                   decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND                               decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED                 decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND                          decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED            decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND                        decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED          decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND                                 decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED                   decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND                       decimal(22, 4) NULL
, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND             decimal(22, 4) NULL
, STARTED_AT                                                                       varchar(20) NOT NULL
, FINISHED_AT                                                                      varchar(20) NOT NULL
);

CREATE UNIQUE INDEX ux_f_dtl_labour_force_hrs_wrkd_m ON ltn.dbo.f_dtl_labour_force_hrs_wrkd_m(period_capture_id);

ALTER TABLE ltn.dbo.f_dtl_labour_force_hrs_wrkd_m REBUILD
WITH(DATA_COMPRESSION = ROW);

=======================================================================================================================================================================================================

exec create_f_dtl_labour_force_hrs_wrkd_m @p_env = 'PROD', @p_task_nme = '', @p_pkg_nme = ''


select * from LTN.DBO.F_DTL_LABOUR_FORCE_HRS_WRKD_M order by 2
*/

USE [ltn]
GO

IF OBJECT_ID('create_f_dtl_labour_force_hrs_wrkd_m') IS NULL -- Check if SP Exists
 EXEC('CREATE PROCEDURE create_f_dtl_labour_force_hrs_wrkd_m AS SET NOCOUNT ON;') -- Create dummy/empty SP
GO
 
alter procedure create_f_dtl_labour_force_hrs_wrkd_m -- Alter the SP Always
(
  @p_env nvarchar (10) 
, @p_task_nme nvarchar (100) 
, @p_pkg_nme nvarchar (100)
) 
as

BEGIN

SET LANGUAGE 'british english'; -- sets the date viewer to show dates as YYYY-MM-DD

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

/*
=======================================================================================================================================================================================================
DECLARATIONS & INITIALISATIONS
=======================================================================================================================================================================================================
*/
-- TABLES ----------------------------------------------------------------
declare @l_tbl_nme as nvarchar (50);
declare @l_tmp_tbl_nme as nvarchar (50);
declare @l_prces_dte_id as nvarchar(8);
      
set @l_tbl_nme = 'f_dtl_labour_force_hrs_wrkd_m';
set @l_prces_dte_id = CONVERT( VARCHAR(10), CAST(cast(getdate() as date) AS DATE), 112);
	 
/*
=======================================================================================================================================================================================================
MAIN CODE BLOCK
- TABLE TIDY UP (IF NEEDED)
- INSERT NEW DATA
- SWITCH INTO EMPTY PARTITIONS (IF USING TABLE PARTITIONS)
=======================================================================================================================================================================================================
*/

/*
=======================================================================================================================================================================================================
TRY BLOACK - START
=======================================================================================================================================================================================================
*/
    BEGIN TRY

/*
STEP 1 
---------------------------------------------------------------------------------------------------
** load data from sqlite3 database to sqlserver temp table
drop table #TMP_DTL_LABOUR_FORCE_HRS_WRKD_M
*/ 
	   CREATE TABLE #TMP_DTL_LABOUR_FORCE_HRS_WRKD_M
	   ( MSMT_DTE_ID                                                                      integer NOT NULL
	   , CAPTURE_PERIOD_ID                                                                integer NOT NULL
	   , CAPTURE_PERIOD                                                                   date NOT NULL
	   , CNTRY_CDE                                                                        varchar(2) NOT NULL
	   , SITE_CDE                                                                         varchar(20) NOT NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND                                  decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED                    decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND                                    decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED                      decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND                                  decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED                    decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND               decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND                 decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED   decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND               decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND               decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND                  decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED    decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND               decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND                          decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED            decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND                                 decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED                   decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND                               decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED                 decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND                          decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED            decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND                        decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED          decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND                                 decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED                   decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND                       decimal(22, 4) NULL
	   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND             decimal(22, 4) NULL
	   , STARTED_AT                                                                       varchar(20) NOT NULL
	   , FINISHED_AT                                                                      varchar(20) NOT NULL
	   );

	   INSERT INTO #TMP_DTL_LABOUR_FORCE_HRS_WRKD_M ( MSMT_DTE_ID
										   , CAPTURE_PERIOD_ID
										   , CAPTURE_PERIOD
										   , CNTRY_CDE
										   , SITE_CDE
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND
										   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND
										   , STARTED_AT
										   , FINISHED_AT
										   )
	   SELECT MSMT_DTE_ID
		   , convert( varchar(10), cast(CAPTURE_PERIOD AS date), 112) AS CAPTURE_PERIOD_ID
		   , CAPTURE_PERIOD		   
		   , CNTRY_CDE
		   , SITE_CDE
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND
		   , MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND
		   , STARTED_AT
		   , FINISHED_AT
		FROM openquery(PY_WEB_DATA, '
							  SELECT  DAT.MSMT_DTE_ID
								    ,DAT.CAPTURE_PERIOD
								    ,DAT.CNTRY_CDE
								    ,DAT.SITE_CDE
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND
								    ,DAT.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND
								    ,DAT.STARTED_AT
								    ,DAT.FINISHED_AT
								FROM PY_LABOUR_FORCE_AU_HRS_WRKD AS DAT');

/*
STEP 2 
---------------------------------------------------------------------------------------------------
** insert into final f_dtl table 
** only insert missing records from the fact table (exist in sqlite3 db but not in sqlserver)
truncate table LTN.DBO.F_DTL_LABOUR_FORCE_STATUS_M
*/
	   INSERT INTO LTN.DBO.F_DTL_LABOUR_FORCE_HRS_WRKD_M ( MSMT_DTE_ID
												, CAPTURE_PERIOD_ID
												, CAPTURE_PERIOD
												, CNTRY_CDE
												, SITE_CDE
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND
												, MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND
												, STARTED_AT
												, FINISHED_AT
												)
	   SELECT TMP.MSMT_DTE_ID
			 , TMP.CAPTURE_PERIOD_ID
			 , TMP.CAPTURE_PERIOD
			 , TMP.CNTRY_CDE
			 , TMP.SITE_CDE
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_PERSONS__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_MALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_FEMALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_PERSONS__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_MALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_FULL_TIME_FEMALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_PERSONS__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIMEMALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_EMPLOYED_PART_TIME_FEMALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NEW_SOUTH_WALES__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_VICTORIA__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_QUEENSLAND__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_SOUTH_AUSTRALIA__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_WESTERN_AUSTRALIA__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_TASMANIA__SEASONALLY_ADJUSTED
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_NORTHERN_TERRITORY__TREND
			 , TMP.MONTHLY_HOURS_WORKED_IN_ALL_JOBS_AUSTRALIAN_CAPITAL_TERRITORY__TREND
			 , TMP.STARTED_AT
			 , TMP.FINISHED_AT
		  FROM #TMP_DTL_LABOUR_FORCE_HRS_WRKD_M AS TMP
			 LEFT OUTER JOIN LTN.DBO.F_DTL_LABOUR_FORCE_HRS_WRKD_M AS DTL
			 ON 1 = 1
				AND TMP.CAPTURE_PERIOD_ID = DTL.CAPTURE_PERIOD_ID
		  WHERE 1 = 1
			 AND DTL.CAPTURE_PERIOD_ID IS NULL
		  ORDER BY 2;
						 
    END TRY
/*
=======================================================================================================================================================================================================
TRY BLOACK - END
=======================================================================================================================================================================================================
*/

/*
=======================================================================================================================================================================================================
CATCH BLOACK - START
=======================================================================================================================================================================================================
*/

    BEGIN CATCH

        INSERT INTO ltn.dbo.ctl_ssis_err_log
            (msmt_dte_id
            , env
            , job_nme
            , task_nme
            , task_tp
            , task_start_datetime
            , task_end_datetime
            , task_status
            , task_output
            )
        SELECT CONVERT(varchar(10), CAST(GETDATE() AS date), 112) AS msmt_dte_id
            , @p_env
            , @p_pkg_nme
            , @p_task_nme
            , 'SQLSCRIPT'
            , GETDATE()
            , GETDATE()
            , CASE
                WHEN ERROR_MESSAGE() IS NULL
                THEN 'SUCCESS'
                ELSE 'ERROR'
            END
            , 'msmt_dte_id variable used : '+CONVERT( varchar(10), CAST(GETDATE() AS date), 112)+' --- error msg : '+ERROR_MESSAGE();

    END CATCH;

/*
=======================================================================================================================================================================================================
CATCH BLOACK - END
=======================================================================================================================================================================================================
*/

END;
